version: "3.9"

name: aicc-stack
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: aicc-rp
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    networks: [net]

  aicc-api:
    image: ainhn/aicc:back-latest
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - redis_run:/var/run/redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aicc-redis
    restart: unless-stopped
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis:/var/run/redis
      - ./redis-data:/data
    networks: [net]

networks:
  net:
    driver: bridge