name: CI Pipeline - Merge

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "src/**"
      - "package*.json"
      - "src/infra/nginx/nginx.conf"
      - "src/infra/redis/redis.conf"
      - "docker-compose.yml"

env:
  IMAGE_NAME: einhn/aicc-back
  LATEST_TAG: arm64-latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # amd64 러너에서 arm64 빌드
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # main 푸시인 경우에만 로그인/푸시
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # build + push
      - name: Build & Push (ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
            ${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max